index:
  credentials: [[admins, gerkud, zerbitzu, arrunta]]

show:
  credentials: [[admins, gerkud, zerbitzu, arrunta]]

new:
  credentials: admins

create:
  credentials: [[admins, gerkud, zerbitzu, arrunta]]

edit:
  credentials: admins

update:
  credentials: admins

delete:
  credentials: admins
