index:
  credentials: [[admins, gerkud]]

show:
  credentials: [[admins, gerkud]]

new:
  credentials: admins

create:
  credentials: admins

edit:
  credentials: admins

update:
  credentials: admins

delete:
  credentials: admins