index:
  credentials: [[admins, gerkud, zerbitzu, arrunta]]

show:
  credentials: [[admins, gerkud, zerbitzu, arrunta]]

new:
  credentials: [[admins, gerkud, zerbitzu, arrunta]]

create:
  credentials: [[admins, gerkud, zerbitzu, arrunta]]

edit:
  credentials: [[admins, gerkud]]

update:
  credentials: [[admins, gerkud, zerbitzu]]

delete:
  credentials: admins