index:
  credentials: [[admins, gerkud, zerbitzu, arrunta]]

show:
  credentials: [[admins, gerkud, zerbitzu, arrunta]]

new:
  credentials: admins

create:
  credentials: admins

edit:
  credentials: [[admins, gerkud, zerbitzu, arrunta]]

update:
  credentials: [[admins, gerkud, zerbitzu, arrunta]]

delete:
  credentials: admins
