# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App

prod:
  sf_guard_plugin:
    success_signout_url: /app.php/
dev:
  sf_guard_plugin:
    success_signout_url: /app_dev.php/

all:
  sf_guard_plugin:
    check_password_callable: [bhLDAPAuth, checkPassword]
  sfDependentSelectPlugin:
    js: full
  google:
    maps_api_keys:
      default:
    helbidea: 20100, ERRENTERIA
  erakundea: ERRENTERIAKO UDALA
  pdf_goiburua: Gertakari Zerrenda
  abisuak_nork: gerkud@example.org
  gertakariak_orriko: 30
  #proxy: 127.0.0.1:3128
  data_formatoa: Y-m-d
  sortze_data_automatikoa: true
  balidatu:
    aurreikuspen_datak: true
  zerrendatua:
    iragazkiak_erakutsi: true
  #Aukeratu daitezkeen zutabeen zerrenda osoa:
  #  id, laburpena, klasea, mota, azpimota, abisuanork, egoera, saila, langilea, barrutia, kalea,
  #  kale_zbkia, deskribapena, ixte_data, hasiera_aurreikusia, amaiera_aurreikusia, lehentasuna,
  #  jatorrizkosaila, eraikina, created_at, updated_at, eraikinakalea
  zutabeak:
    eskaerak: [lehentasuna, id, created_at, mota, auzoa, eraikinakalea, laburpena, abisuanork]
    gertakariak: [lehentasuna, id, created_at, saila, auzoa, eraikinakalea, laburpena, egoera, abisuanork, updated_at]
  ordenaketa:
    eskaerak: [created_at DESC]
    gertakariak: [created_at DESC]
  gerkud:
    eremuak: [id, laburpena, klasea, mota, azpimota, abisuanork, egoera, saila, langilea, auzoa, kalea, kale_zbkia, deskribapena, ixte_data, hasiera_aurreikusia, amaiera_aurreikusia, lehentasuna, jatorrizkosaila, eraikina, created_at, updated_at]
    derrigorrezkoak: [id,  created_at, laburpena, mota, lehentasuna]
    kopia_zehatza: true
    izena_eta_abizena: false