# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: gertakaria, action: index }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module/:sf_culture/
  param: { action: index }
  requirements:
    sf_culture: (?:eu|es)

default:
  url:   /:module/:sf_culture/:action/*

langilea:
  url:  /nere_datuak/:sf_culture
  param: { module: langilea, action: edit }

gertakari_bilaketa:
  url:   /bilaketa
  param: { module: gertakaria, action: search }

