# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/08-Security

#default:
#  is_secure: false

# don't secure login or error pages or you'll make a loop.
login:
  is_secure: off
  require_ssl: false

error404:
  is_secure: off
  require_ssl: false

disabled:
  is_secure: off
  require_ssl: false

# require authnz for everything else
default:
  is_secure: on
  credentials: [[admins, gerkud]]
