# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/04-Settings

prod:
  .settings:
    no_script_name:         false
    logging_enabled:        false

dev:
  .settings:
    error_reporting:        <?php echo (E_ALL | E_STRICT)."\n" ?>
    web_debug:              true
    cache:                  false
    no_script_name:         false
    etag:                   false

test:
  .settings:
    error_reporting:        <?php echo ((E_ALL | E_STRICT) ^ E_NOTICE)."\n" ?>
    cache:                  false
    web_debug:              false
    no_script_name:         false
    etag:                   false

all:
  .settings:
    enabled_modules: [default, sfGuardAuth, bhLDAPAuth, sfGuardUser, sfEasyGMapPlugin]
    # Form security secret (CSRF protection)
#    csrf_secret:            c4a071800fb964813c9863793f9c9fb67dfc79ac

    # Output escaping settings
    escaping_strategy:      true
    escaping_method:        ESC_SPECIALCHARS

    # Internacionalizacion
    charset: utf-8
    i18n: true
    default_culture: eu_ES
    standard_helpers: [Partial, I18N]

    # Enable the database manager
    use_database:           true

    upload_dir: %GERKUD_UPLOAD_DIR%

  .actions:
    secure_module:          login
    secure_action:          secure
    login_module:           login
    login_action:           signin
    error_400_module:       erroreak
    error_400_action:       error
    error_401_module:       erroreak
    error_401_action:       error
    error_403_module:       erroreak
    error_403_action:       error
    error_404_module:       erroreak
    error_404_action:       error
    error_500_module:       erroreak
    error_500_action:       error
    error_501_module:       erroreak
    error_501_action:       error
    error_502_module:       erroreak
    error_502_action:       error
    error_503_module:       erroreak
    error_503_action:       error
    error_504_module:       erroreak
    error_504_action:       error
#    login_module:           sfGuardAuth
#    login_action:           signin
#    secure_module:          sfGuardAuth
#    secure_action:          secure
