index:
  credentials: [[admins, gerkud, zerbitzu]]

show:
  credentials: [[admins, gerkud, zerbitzu]]

new:
  credentials: admins

create:
  credentials: admins

edit:
  credentials: admins

update:
  credentials: admins

delete:
  credentials: admins