Gertakaria:
  actAs:
    Timestampable: ~
  columns:
    laburpena: { type: string(255) }
    klasea_id: { type: integer, notnull: false }
    mota_id: { type: integer, notnull: true }
    azpimota_id:  { type: integer, notnull: false }
    abisuaNork: { type: string(512) }
    egoera_id: { type: integer, notnull: true, default: 1 }
    saila_id: { type: integer, notnull: false }
    langilea_id: { type: integer, notnull: false }
    barrutia_id: {type: integer, notnull: false }
    kalea_id: { type: integer, notnull: false }
    kale_zbkia: { type: string(50) }
    deskribapena: { type: string(4000), notnull: false }
    ixte_data: { type: datetime, notnull: false }
    hasiera_aurreikusia: { type: date, notnull: false }
    amaiera_aurreikusia: { type: date, notnull: false }
    lehentasuna_id: { type: integer, notnull: true, default: 1 }
    jatorrizkoSaila_id: { type: integer, notnull: false }
    eraikina_id: { type: integer, notnull: false }
  relations:
    Klasea: { onDelete: CASCADE, local: klasea_id, foreign: id }
    Mota: { onDelete: CASCADE, local: mota_id, foreign: id }
    Azpimota: { onDelete: CASCADE, local: azpimota_id, foreign: id }
    Barrutia: { onDelete: CASCADE, local: barrutia_id, foreign: id }
    Kalea: { onDelete: CASCADE, local: kalea_id, foreign: id }
    Saila: { onDelete: CASCADE, local: saila_id, foreign: id }
    Langilea: { onDelete: CASCADE, local: langilea_id, foreign: id }
    Egoera: { onDelete: CASCADE, local: egoera_id, foreign: id }
    Lehentasuna: { onDelete: CASCADE, local: lehentasuna_id, foreign: id }
    JatorrizkoSaila: { onDelete: CASCADE, local: jatorrizkoSaila_id, foreign: id }
    Eraikina: { onDelete: CASCADE, local: eraikina_id, foreign: id }

Langilea:
  connection: doctrine
  inheritance:
    extends: sfGuardUser
    type: simple
  columns:
    ohartaraztea_id: { type: integer, notnull: false }
  relations:
    Ohartaraztea: { onDelete: CASCADE, local: ohartaraztea_id, foreign: id }

Fitxategia:
  actAs:
    Timestampable: ~
  columns:
    gertakaria_id: { type: integer, notnull: true }
    langilea_id: { type: integer, notnull: false }
    fitxategia: { type: string(255) }
    deskribapena: { type: string(255) }
  relations:
    Gertakaria: { onDelete: CASCADE, local: gertakaria_id, foreign: id }
    Langilea: { onDelete: CASCADE, local: langilea_id, foreign: id }

Iruzkina:
  actAs:
    Timestampable: ~
  columns:
    gertakaria_id: { type: integer, notnull: true }
    langilea_id: { type: integer, notnull: false }
    ekintza_id: { type: integer, notnull: false }
    testua: { type: string(4000) }
  relations:
    Gertakaria: { onDelete: CASCADE, local: gertakaria_id, foreign: id }
    Langilea: { onDelete: CASCADE, local: langilea_id, foreign: id }
    Ekintza: { onDelete: CASCADE, local: ekintza_id, foreign: id }

Ekintza:
  actAs:
    I18n:
      fields: [mota]
  columns:
    mota: { type: string(255) }

Mota:
  actAs:
    I18n:
      fields: [izena]
  columns:
    izena: { type: string(255), notnull: true }

Azpimota:
  actAs:
    I18n:
      fields: [izena]
  columns:
    mota_id:  { type: integer, notnull: true }
    izena: { type: string(255), notnull: true }
  relations:
    Mota: { onDelete: CASCADE, local: mota_id, foreign: id, foreignAlias: Azpimota }

Egoera:
  actAs:
    I18n:
      fields: [izena]
  columns:
    izena: { type: string(255), notnull: true, unique: true }
    kolorea: { type: string(50), notnull:true}

Barrutia:
  actAs:
  columns:
    izena: { type: string(255), notnull: true, unique: true }

Kalea:
  actAs:
  columns:
    barrutia_id:  { type: integer, notnull: true }
    izena: { type: string(255), notnull: true, unique: true }
    google: { type: string(255), notnull: false }
  relations:
    Barrutia: { onDelete: CASCADE, local: barrutia_id, foreign: id }

Saila:
  connection: doctrine
  inheritance:
    extends: sfGuardGroup
    type: simple

SailaMota:
  columns:
    saila_id: { type: integer, notnull: true }
    mota_id: { type: integer, notnull: true }
  relations:
    Saila: { onDelete: CASCADE, local: saila_id, foreign: id }
    Mota: { onDelete: CASCADE, local: mota_id, foreign: id }

SailekoLangileak:
  connection: doctrine
  inheritance:
    extends: sfGuardUserGroup
    type: simple

Planifikazioa:
  actAs:
  columns:
    gertakaria_id: { type: integer, notnull: true }
    langilea_id: { type: integer, notnull: true }
    hasiera_data: {type: date, notnull: true }
    hasiera_ordua_noiztik: {type: time, notnull: true }
    hasiera_ordua_noizarte: {type: time, notnull: true }
    amaiera_data: {type: date, notnull: true }
    amaiera_ordua_noiztik: {type: time, notnull: true }
    amaiera_ordua_noizarte: {type: time, notnull: true }
  relations:
    Gertakaria: { onDelete: CASCADE, local: gertakaria_id, foreign: id }
    Langilea: { onDelete: CASCADE, local: langilea_id, foreign: id }

Lehentasuna:
  actAs:
    I18n:
      fields: [izena]
  columns:
    izena: { type: string(255), notnull: true, unique: true }
    kolorea: { type: string(50), notnull:false}

Geo:
  actAs:
  columns:
    gertakaria_id: { type: integer, notnull: true }
    longitudea: { type: double(18), scale: 6, notnull: true }
    latitudea: { type: double(18), scale: 6, notnull: true }
    testua: { type: string(50) }
    geometria_id: { type: integer, notnull: true }
  relations:
    Gertakaria: { onDelete: CASCADE, local: gertakaria_id, foreign: id }
    Geometria: { onDelete: CASCADE, local: geometria_id, foreign: id }

Geometria:
  actAs:
  columns:
    mota: { type: string(50) }

Klasea:
  actAs:
    I18n:
      fields: [izena]
  columns:
    izena: { type: string(255), notnull: true }

JatorrizkoSaila:
  actAs:
    I18n:
      fields: [izena]
  columns:
    izena: { type: string(255), notnull: true }

Ohartaraztea:
  actAs:
    I18n:
      fields: [mota]
  columns:
    mota: { type: string(255), notnull: true }

Eraikina:
  actAs:
  columns:
    izena: { type: string(255), notnull: true }
    barrutia_id:  { type: integer, notnull: true }
    longitudea: { type: double(18), scale: 6, notnull: true }
    latitudea: { type: double(18), scale: 6, notnull: true }
  relations:
    Barrutia: { onDelete: CASCADE, local: barrutia_id, foreign: id }

EgunTarteak:
  columns:
    minimoa: { type: integer, notnull: true, unique: true }
    maximoa: { type: integer, notnull: true, unique: true }
