Gertakaria:
  actAs:
    Timestampable: ~
  columns:
    laburpena: { type: string(255) }
    klasea_id: { type: integer, notnull: false }
    mota_id: { type: integer, notnull: false }
    azpimota_id:  { type: integer, notnull: false }
    abisuaNork: { type: string(512) }
    egoera_id: { type: integer, notnull: true, default: 1 }
    saila_id: { type: integer, notnull: false }
    langilea_id: { type: integer, notnull: false }
    barrutia_id: {type: integer, notnull: false }
    auzoa_id: {type: integer, notnull: false }
    kalea_id: { type: integer, notnull: false }
    kale_zbkia: { type: string(50) }
    deskribapena: { type: string(4000), notnull: false }
    ixte_data: { type: timestamp, notnull: false }
    hasiera_aurreikusia: { type: date, notnull: false }
    amaiera_aurreikusia: { type: date, notnull: false }
    lehentasuna_id: { type: integer, notnull: false}
    jatorrizkoSaila_id: { type: integer, notnull: false }
    eraikina_id: { type: integer, notnull: false }
    herritarrena: { type: boolean, notnull: false }
    kontaktua_id: { type: integer, notnull: false }
    espedientea: { type: string(12), notnull: false }
  relations:
    Klasea: { onDelete: RESTRICT, local: klasea_id, foreign: id }
    Mota: { onDelete: RESTRICT, local: mota_id, foreign: id }
    Azpimota: { onDelete: RESTRICT, local: azpimota_id, foreign: id }
    Barrutia: { onDelete: RESTRICT, local: barrutia_id, foreign: id }
    Auzoa: { onDelete: RESTRICT, local: auzoa_id, foreign: id }
    Kalea: { onDelete: RESTRICT, local: kalea_id, foreign: id }
    Saila: { onDelete: RESTRICT, local: saila_id, foreign: id }
    Langilea: { onDelete: RESTRICT, local: langilea_id, foreign: id }
    Egoera: { onDelete: RESTRICT, local: egoera_id, foreign: id }
    Lehentasuna: { onDelete: RESTRICT, local: lehentasuna_id, foreign: id }
    JatorrizkoSaila: { onDelete: RESTRICT, local: jatorrizkoSaila_id, foreign: id }
    Eraikina: { onDelete: RESTRICT, local: eraikina_id, foreign: id }
    Kontaktua:
      foreignType: one

Langilea:
  connection: doctrine
  inheritance:
    extends: sfGuardUser
    type: simple
  columns:
    ohartaraztea_id: { type: integer, notnull: false }
  relations:
    Ohartaraztea: { onDelete: RESTRICT, local: ohartaraztea_id, foreign: id }

Fitxategia:
  actAs:
    Timestampable: ~
  columns:
    gertakaria_id: { type: integer, notnull: true }
    langilea_id: { type: integer, notnull: false }
    fitxategia: { type: string(255) }
    deskribapena: { type: string(255) }
  relations:
    Gertakaria: { onDelete: RESTRICT, local: gertakaria_id, foreign: id }
    Langilea: { onDelete: RESTRICT, local: langilea_id, foreign: id }

Iruzkina:
  actAs:
    Timestampable: ~
  columns:
    gertakaria_id: { type: integer, notnull: true }
    langilea_id: { type: integer, notnull: false }
    ekintza_id: { type: integer, notnull: false }
    testua: { type: string(4000) }
  relations:
    Gertakaria: { onDelete: RESTRICT, local: gertakaria_id, foreign: id }
    Langilea: { onDelete: RESTRICT, local: langilea_id, foreign: id }
    Ekintza: { onDelete: RESTRICT, local: ekintza_id, foreign: id }

Ekintza:
  actAs:
    I18n:
      fields: [mota]
  columns:
    mota: { type: string(255) }

Mota:
  actAs:
    I18n:
      fields: [izena]
  columns:
    izena: { type: string(255), notnull: true }

Azpimota:
  actAs:
    I18n:
      fields: [izena]
  columns:
    mota_id:  { type: integer, notnull: true }
    izena: { type: string(255), notnull: true }
  relations:
    Mota: { onDelete: RESTRICT, local: mota_id, foreign: id, foreignAlias: Azpimota }

Egoera:
  actAs:
    I18n:
      fields: [izena]
  columns:
    izena: { type: string(255), notnull: true, unique: true }
    kolorea: { type: string(50), notnull:true}

Barrutia:
  actAs:
  columns:
    izena: { type: string(255), notnull: true, unique: true }

Auzoa:
  actAs:
  columns:
    barrutia_id: { type: integer, notnull: false }
    izena: { type: string(255), notnull: true, unique: true }
  relations:
    Barrutia: { onDelete: RESTRICT, local: barrutia_id, foreign: id }

Kalea:
  actAs:
  columns:
    barrutia_id: { type: integer, notnull: false }
    auzoa_id: { type: integer, notnull: false }
    izena: { type: string(255), notnull: true, unique: true }
    google: { type: string(255), notnull: false }
  relations:
    Barrutia: { onDelete: RESTRICT, local: barrutia_id, foreign: id }
    Auzoa: { onDelete: RESTRICT, local: auzoa_id, foreign: id }

Saila:
  connection: doctrine
  inheritance:
    extends: sfGuardGroup
    type: simple

SailaMota:
  columns:
    saila_id: { type: integer, notnull: true }
    mota_id: { type: integer, notnull: true }
  relations:
    Saila: { onDelete: RESTRICT, local: saila_id, foreign: id }
    Mota: { onDelete: RESTRICT, local: mota_id, foreign: id }

SailekoLangileak:
  connection: doctrine
  inheritance:
    extends: sfGuardUserGroup
    type: simple

Planifikazioa:
  actAs:
  columns:
    gertakaria_id: { type: integer, notnull: true }
    langilea_id: { type: integer, notnull: true }
    hasiera_data: {type: date, notnull: true }
    hasiera_ordua_noiztik: {type: time, notnull: true }
    hasiera_ordua_noizarte: {type: time, notnull: true }
    amaiera_data: {type: date, notnull: true }
    amaiera_ordua_noiztik: {type: time, notnull: true }
    amaiera_ordua_noizarte: {type: time, notnull: true }
  relations:
    Gertakaria: { onDelete: RESTRICT, local: gertakaria_id, foreign: id }
    Langilea: { onDelete: RESTRICT, local: langilea_id, foreign: id }

Lehentasuna:
  actAs:
    I18n:
      fields: [izena]
  columns:
    izena: { type: string(255), notnull: true, unique: true }
    kolorea: { type: string(50), notnull:false}

Geo:
  actAs:
  columns:
    gertakaria_id: { type: integer, notnull: true }
    longitudea: { type: double(18), scale: 6, notnull: true }
    latitudea: { type: double(18), scale: 6, notnull: true }
    zehaztasuna: { type: double(18), scale: 6, notnull: false }
    testua: { type: string(50) }
    geometria_id: { type: integer, notnull: true }
  relations:
    Gertakaria: { onDelete: RESTRICT, local: gertakaria_id, foreign: id }
    Geometria: { onDelete: RESTRICT, local: geometria_id, foreign: id }

Geometria:
  actAs:
  columns:
    mota: { type: string(50) }

Klasea:
  actAs:
    I18n:
      fields: [izena]
  columns:
    izena: { type: string(255), notnull: true }

JatorrizkoSaila:
  actAs:
    I18n:
      fields: [izena]
  columns:
    izena: { type: string(255), notnull: true }

Ohartaraztea:
  actAs:
    I18n:
      fields: [mota]
  columns:
    mota: { type: string(255), notnull: true }

Eraikina:
  actAs:
  columns:
    izena: { type: string(255), notnull: true }
    barrutia_id: { type: integer, notnull: false }
    auzoa_id: { type: integer, notnull: false }
    longitudea: { type: double(18), scale: 6, notnull: true }
    latitudea: { type: double(18), scale: 6, notnull: true }
  relations:
    Barrutia: { onDelete: RESTRICT, local: barrutia_id, foreign: id }
    Auzoa: { onDelete: RESTRICT, local: auzoa_id, foreign: id }

EgunTarteak:
  columns:
    minimoa: { type: integer, notnull: true, unique: true }
    maximoa: { type: integer, notnull: true, unique: true }

ErlazioMota:
  actAs:
    I18n:
      fields: [izena]
  columns:
    izena: { type: string(255), notnull: true }

Erlazioak:
  columns:
    hasiera_id: { type: integer, notnull: true }
    amaiera_id: { type: integer, notnull: true }
    erlazio_mota_id: { type: integer, notnull: false }
  relations:
    ErlazioMota:
      onDelete: RESTRICT
      local: erlazio_mota_id
      foreign: id
      type: one
    Gertakaria:
      onDelete: RESTRICT
      local: amaiera_id
      foreign: id
      type: one
    Gertakaria_3:
      onDelete: RESTRICT
      class: Gertakaria
      local: hasiera_id
      foreign: id
      type: one

Kontaktua:
  columns:
    izena: { type: string(255), notnull: false }
    abizenak: { type: string(255), notnull: false }
    nan: { type: string(9), notnull: false }
    posta: { type: string(100), notnull: false }
    telefonoa: { type: string(30), notnull: false }
    ohartarazi: { type: integer, notnull: false }
    hizkuntza: { type: string(2), notnull: false }
  relations:
    KontaktuaOhartaraztea:
      local: ohartarazi
      foreign: id
      type: one

KontaktuaOhartaraztea:
  actAs:
    I18n:
      fields: [modua]
  columns:
    ordena: { type: integer, notnull: false }
    modua: { type: string(100), notnull: true }
